package whatisnewin.javax.net.ssl;

import javax.net.ssl.HttpsURLConnection;
import java.util.Optional;
import javax.net.ssl.SSLSession;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link HttpsURLConnection}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link HttpsURLConnection} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see HttpsURLConnection
 */
public final class WhatIsNewInHttpsURLConnection
{
  /**
   * Example call to new method {@link HttpsURLConnection#getSSLSession()}.
   * @since 12
   * @see HttpsURLConnection#getSSLSession()
   */
  public Optional<SSLSession> getSSLSession()
  {
    HttpsURLConnection testee = $$$();

    Optional<SSLSession> result = testee.getSSLSession();
    return result;
  }

  private HttpsURLConnection $$$()
  {
    return null;
  }
}
