package whatisnewin.com.sun.source.doctree;

import com.sun.source.doctree.DocTreeVisitor;
import com.sun.source.doctree.SystemPropertyTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link DocTreeVisitor}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link DocTreeVisitor} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see DocTreeVisitor
 */
public final class WhatIsNewInDocTreeVisitor<R, P>
{
  /**
   * Example call to new method {@link DocTreeVisitor#visitSystemProperty(SystemPropertyTree, Object)}.
   * @since 12
   * @see DocTreeVisitor#visitSystemProperty(SystemPropertyTree, Object)
   */
  public R visitSystemProperty(SystemPropertyTree node, P p)
  {
    DocTreeVisitor<R, P> testee = $$$();

    R result = testee.visitSystemProperty(node, p);
    return result;
  }

  private DocTreeVisitor $$$()
  {
    return null;
  }
}
