package whatisnewin.com.sun.source.doctree;

import com.sun.source.doctree.SystemPropertyTree;
import javax.lang.model.element.Name;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SystemPropertyTree}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link SystemPropertyTree} is a completely new class.
 * @since 12
 * @see SystemPropertyTree
 */
public final class WhatIsNewInSystemPropertyTree
{
  /**
   * Example call to new method {@link SystemPropertyTree#getPropertyName()}.
   * @since 12
   * @see SystemPropertyTree#getPropertyName()
   */
  public Name getPropertyName()
  {
    SystemPropertyTree testee = $$$();

    Name result = testee.getPropertyName();
    return result;
  }

  private SystemPropertyTree $$$()
  {
    return null;
  }
}
