package whatisnewin.java.lang.invoke;

import java.lang.invoke.TypeDescriptor;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TypeDescriptor}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link TypeDescriptor} is a completely new class.
 * @since 12
 * @see TypeDescriptor
 */
public final class WhatIsNewInTypeDescriptor
{
  /**
   * Example call to new method {@link TypeDescriptor#descriptorString()}.
   * @since 12
   * @see TypeDescriptor#descriptorString()
   */
  public String descriptorString()
  {
    TypeDescriptor testee = $$$();

    String result = testee.descriptorString();
    return result;
  }

  private TypeDescriptor $$$()
  {
    return null;
  }
}
