package whatisnewin.java.lang.invoke;

import java.lang.invoke.MethodHandle;
import java.util.Optional;
import java.lang.constant.MethodHandleDesc;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link MethodHandle}
 * that were newly introduced in Java versions 12.<br>
 *
 * {@link MethodHandle} is an old class but has new fields, constructors or methods
 * @since 1.7
 * @see MethodHandle
 */
public final class WhatIsNewInMethodHandle
{
  /**
   * Example call to new method {@link MethodHandle#describeConstable}
   * @since 12
   * @see MethodHandle#describeConstable
   */
  public Optional<MethodHandleDesc> describeConstable()
  {
    MethodHandle testee = $$$();

    Optional<MethodHandleDesc> result = testee.describeConstable();
    return result;
  }

  private MethodHandle $$$()
  {
    return null;
  }
}
