package whatisnewin.java.lang.invoke;

import java.lang.invoke.VarHandle;
import java.util.Optional;
import java.lang.invoke.VarHandle.VarHandleDesc;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link VarHandle}
 * that were newly introduced in Java versions 12.<br>
 *
 * {@link VarHandle} is an old class but has new fields, constructors or methods
 * @since 9
 * @see VarHandle
 */
public final class WhatIsNewInVarHandle
{
  /**
   * Example call to new method {@link VarHandle#describeConstable}
   * @since 12
   * @see VarHandle#describeConstable
   */
  public Optional<VarHandleDesc> describeConstable()
  {
    VarHandle testee = $$$();

    Optional<VarHandleDesc> result = testee.describeConstable();
    return result;
  }

  private VarHandle $$$()
  {
    return null;
  }
}
