package whatisnewin.java.net;

import java.net.SecureCacheResponse;
import java.util.Optional;
import javax.net.ssl.SSLSession;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SecureCacheResponse}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link SecureCacheResponse} is an old class but has new fields, constructors or methods.
 * @since 1.5
 * @see SecureCacheResponse
 */
public final class WhatIsNewInSecureCacheResponse
{
  /**
   * Example call to new method {@link SecureCacheResponse#getSSLSession()}.
   * @since 12
   * @see SecureCacheResponse#getSSLSession()
   */
  public Optional<SSLSession> getSSLSession()
  {
    SecureCacheResponse testee = $$$();

    Optional<SSLSession> result = testee.getSSLSession();
    return result;
  }

  private SecureCacheResponse $$$()
  {
    return null;
  }
}
