package whatisnewin.java.net;

import java.net.ServerSocket;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ServerSocket}
 * that were newly introduced in Java versions 12.<br>
 *
 * {@link ServerSocket} is an old class but has new fields, constructors or methods
 * @since 1.0
 * @see ServerSocket
 */
public final class WhatIsNewInServerSocket
{
}
