package whatisnewin.java.lang;

import java.lang.Character.UnicodeBlock;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link UnicodeBlock}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link UnicodeBlock} is an old class but has new fields, constructors or methods.
 * @since 1.2
 * @see UnicodeBlock
 */
public final class WhatIsNewInCharacter$UnicodeBlock
{
  /**
   * Example usage of the new field {@link UnicodeBlock#GEORGIAN_EXTENDED}.
   * @since 12
   * @see UnicodeBlock#GEORGIAN_EXTENDED
   */
  public static final UnicodeBlock GEORGIAN_EXTENDED = UnicodeBlock.GEORGIAN_EXTENDED;

  /**
   * Example usage of the new field {@link UnicodeBlock#HANIFI_ROHINGYA}.
   * @since 12
   * @see UnicodeBlock#HANIFI_ROHINGYA
   */
  public static final UnicodeBlock HANIFI_ROHINGYA = UnicodeBlock.HANIFI_ROHINGYA;

  /**
   * Example usage of the new field {@link UnicodeBlock#OLD_SOGDIAN}.
   * @since 12
   * @see UnicodeBlock#OLD_SOGDIAN
   */
  public static final UnicodeBlock OLD_SOGDIAN = UnicodeBlock.OLD_SOGDIAN;

  /**
   * Example usage of the new field {@link UnicodeBlock#SOGDIAN}.
   * @since 12
   * @see UnicodeBlock#SOGDIAN
   */
  public static final UnicodeBlock SOGDIAN = UnicodeBlock.SOGDIAN;

  /**
   * Example usage of the new field {@link UnicodeBlock#DOGRA}.
   * @since 12
   * @see UnicodeBlock#DOGRA
   */
  public static final UnicodeBlock DOGRA = UnicodeBlock.DOGRA;

  /**
   * Example usage of the new field {@link UnicodeBlock#GUNJALA_GONDI}.
   * @since 12
   * @see UnicodeBlock#GUNJALA_GONDI
   */
  public static final UnicodeBlock GUNJALA_GONDI = UnicodeBlock.GUNJALA_GONDI;

  /**
   * Example usage of the new field {@link UnicodeBlock#MAKASAR}.
   * @since 12
   * @see UnicodeBlock#MAKASAR
   */
  public static final UnicodeBlock MAKASAR = UnicodeBlock.MAKASAR;

  /**
   * Example usage of the new field {@link UnicodeBlock#MEDEFAIDRIN}.
   * @since 12
   * @see UnicodeBlock#MEDEFAIDRIN
   */
  public static final UnicodeBlock MEDEFAIDRIN = UnicodeBlock.MEDEFAIDRIN;

  /**
   * Example usage of the new field {@link UnicodeBlock#MAYAN_NUMERALS}.
   * @since 12
   * @see UnicodeBlock#MAYAN_NUMERALS
   */
  public static final UnicodeBlock MAYAN_NUMERALS = UnicodeBlock.MAYAN_NUMERALS;

  /**
   * Example usage of the new field {@link UnicodeBlock#INDIC_SIYAQ_NUMBERS}.
   * @since 12
   * @see UnicodeBlock#INDIC_SIYAQ_NUMBERS
   */
  public static final UnicodeBlock INDIC_SIYAQ_NUMBERS = UnicodeBlock.INDIC_SIYAQ_NUMBERS;

  /**
   * Example usage of the new field {@link UnicodeBlock#CHESS_SYMBOLS}.
   * @since 12
   * @see UnicodeBlock#CHESS_SYMBOLS
   */
  public static final UnicodeBlock CHESS_SYMBOLS = UnicodeBlock.CHESS_SYMBOLS;

}
