package whatisnewin.java.lang;

import java.util.Optional;
import java.lang.invoke.MethodHandles.Lookup;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Float}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link Float} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Float
 */
public final class WhatIsNewInFloat
{
  /**
   * Example call to new method {@link Float#describeConstable()}.
   * @since 12
   * @see Float#describeConstable()
   */
  public Optional<Float> describeConstable()
  {
    Float testee = $$$();

    Optional<Float> result = testee.describeConstable();
    return result;
  }

  /**
   * Example call to new method {@link Float#resolveConstantDesc(Lookup)}.
   * @since 12
   * @see Float#resolveConstantDesc(Lookup)
   */
  public Float resolveConstantDesc(Lookup lookup)
  {
    Float testee = $$$();

    Float result = testee.resolveConstantDesc(lookup);
    return result;
  }

  private Float $$$()
  {
    return null;
  }
}
