package whatisnewin.java.lang;

import java.lang.Character.UnicodeScript;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link UnicodeScript}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link UnicodeScript} is an old class but has new fields, constructors or methods.
 * @since 1.7
 * @see UnicodeScript
 */
public final class WhatIsNewInCharacter$UnicodeScript
{
  /**
   * Example usage of the new field {@link UnicodeScript#HANIFI_ROHINGYA}.
   * @since 12
   * @see UnicodeScript#HANIFI_ROHINGYA
   */
  public static final UnicodeScript HANIFI_ROHINGYA = UnicodeScript.HANIFI_ROHINGYA;

  /**
   * Example usage of the new field {@link UnicodeScript#OLD_SOGDIAN}.
   * @since 12
   * @see UnicodeScript#OLD_SOGDIAN
   */
  public static final UnicodeScript OLD_SOGDIAN = UnicodeScript.OLD_SOGDIAN;

  /**
   * Example usage of the new field {@link UnicodeScript#SOGDIAN}.
   * @since 12
   * @see UnicodeScript#SOGDIAN
   */
  public static final UnicodeScript SOGDIAN = UnicodeScript.SOGDIAN;

  /**
   * Example usage of the new field {@link UnicodeScript#DOGRA}.
   * @since 12
   * @see UnicodeScript#DOGRA
   */
  public static final UnicodeScript DOGRA = UnicodeScript.DOGRA;

  /**
   * Example usage of the new field {@link UnicodeScript#GUNJALA_GONDI}.
   * @since 12
   * @see UnicodeScript#GUNJALA_GONDI
   */
  public static final UnicodeScript GUNJALA_GONDI = UnicodeScript.GUNJALA_GONDI;

  /**
   * Example usage of the new field {@link UnicodeScript#MAKASAR}.
   * @since 12
   * @see UnicodeScript#MAKASAR
   */
  public static final UnicodeScript MAKASAR = UnicodeScript.MAKASAR;

  /**
   * Example usage of the new field {@link UnicodeScript#MEDEFAIDRIN}.
   * @since 12
   * @see UnicodeScript#MEDEFAIDRIN
   */
  public static final UnicodeScript MEDEFAIDRIN = UnicodeScript.MEDEFAIDRIN;

}
