package whatisnewin.java.lang;

import java.util.Optional;
import java.lang.invoke.MethodHandles.Lookup;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Long}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link Long} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Long
 */
public final class WhatIsNewInLong
{
  /**
   * Example call to new method {@link Long#describeConstable()}.
   * @since 12
   * @see Long#describeConstable()
   */
  public Optional<Long> describeConstable()
  {
    Long testee = $$$();

    Optional<Long> result = testee.describeConstable();
    return result;
  }

  /**
   * Example call to new method {@link Long#resolveConstantDesc(Lookup)}.
   * @since 12
   * @see Long#resolveConstantDesc(Lookup)
   */
  public Long resolveConstantDesc(Lookup lookup)
  {
    Long testee = $$$();

    Long result = testee.resolveConstantDesc(lookup);
    return result;
  }

  private Long $$$()
  {
    return null;
  }
}
