package whatisnewin.java.lang;

import java.util.Optional;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Double}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link Double} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Double
 */
public final class WhatIsNewInDouble
{
  /**
   * Example call to new method {@link Double#describeConstable()}.
   * @since 12
   * @see Double#describeConstable()
   */
  public Optional<Double> describeConstable()
  {
    Double testee = $$$();

    Optional<Double> result = testee.describeConstable();
    return result;
  }

  private Double $$$()
  {
    return null;
  }
}
