package whatisnewin.java.lang;

import java.util.function.Function;
import java.util.Optional;
import java.lang.invoke.MethodHandles.Lookup;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link String}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link String} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see String
 */
public final class WhatIsNewInString
{
  /**
   * Example call to new method {@link String#indent(int)}.
   * @since 12
   * @see String#indent(int)
   */
  public String indent(int n)
  {
    String testee = $$$();

    String result = testee.indent(n);
    return result;
  }

  /**
   * Example call to new method {@link String#transform(Function)}.
   * @since 12
   * @see String#transform(Function)
   */
  public <R> R transform(Function<? super String, ? extends R> f)
  {
    String testee = $$$();

    R result = testee.transform(f);
    return result;
  }

  /**
   * Example call to new method {@link String#describeConstable()}.
   * @since 12
   * @see String#describeConstable()
   */
  public Optional<String> describeConstable()
  {
    String testee = $$$();

    Optional<String> result = testee.describeConstable();
    return result;
  }

  /**
   * Example call to new method {@link String#resolveConstantDesc(Lookup)}.
   * @since 12
   * @see String#resolveConstantDesc(Lookup)
   */
  public String resolveConstantDesc(Lookup lookup)
  {
    String testee = $$$();

    String result = testee.resolveConstantDesc(lookup);
    return result;
  }

  private String $$$()
  {
    return null;
  }
}
