package whatisnewin.java.nio.file;

import java.nio.file.Files;
import java.nio.file.Path;
import java.io.IOException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Files}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link Files} is an old class but has new fields, constructors or methods.
 * @since 1.7
 * @see Files
 */
public final class WhatIsNewInFiles
{
  /**
   * Example call to new method {@link Files#mismatch(Path, Path)}.
   * @since 12
   * @see Files#mismatch(Path, Path)
   */
  public static long mismatch(Path path, Path path2) throws IOException
  {
    long result = Files.mismatch(path, path2);
    return result;
  }

}
