package whatisnewin.javax.swing.filechooser;

import javax.swing.filechooser.FileSystemView;
import java.io.File;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link FileSystemView}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link FileSystemView} is an old class but has new fields, constructors or methods.
 * @since UNDEFINED
 * @see FileSystemView
 */
public final class WhatIsNewInFileSystemView
{
  /**
   * Example call to new method {@link FileSystemView#getChooserShortcutPanelFiles()}.
   * @since 12
   * @see FileSystemView#getChooserShortcutPanelFiles()
   */
  public File[] getChooserShortcutPanelFiles()
  {
    FileSystemView testee = $$$();

    File[] result = testee.getChooserShortcutPanelFiles();
    return result;
  }

  private FileSystemView $$$()
  {
    return null;
  }
}
