package whatisnewin.java.text;

import java.text.NumberFormat.Field;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Field}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link Field} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see Field
 */
public final class WhatIsNewInNumberFormat$Field
{
  /**
   * Example usage of the new field {@link Field#PREFIX}.
   * @since 12
   * @see Field#PREFIX
   */
  public static final Field PREFIX = Field.PREFIX;

  /**
   * Example usage of the new field {@link Field#SUFFIX}.
   * @since 12
   * @see Field#SUFFIX
   */
  public static final Field SUFFIX = Field.SUFFIX;

}
