package whatisnewin.java.text;

import java.text.NumberFormat.Style;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Style}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link Style} is a completely new class.
 * @since 12
 * @see Style
 */
public final class WhatIsNewInNumberFormat$Style
{
  /**
   * Example usage of the new field {@link Style#SHORT}.
   * @since 12
   * @see Style#SHORT
   */
  public static final Style SHORT = Style.SHORT;

  /**
   * Example usage of the new field {@link Style#LONG}.
   * @since 12
   * @see Style#LONG
   */
  public static final Style LONG = Style.LONG;

  /**
   * Example call to new method {@link Style#values()}.
   * @since 12
   * @see Style#values()
   */
  public static Style[] values()
  {
    Style[] result = Style.values();
    return result;
  }

  /**
   * Example call to new method {@link Style#valueOf(String)}.
   * @since 12
   * @see Style#valueOf(String)
   */
  public static Style valueOf(String name)
  {
    Style result = Style.valueOf(name);
    return result;
  }

}
