package whatisnewin.javax.lang.model;

import javax.lang.model.SourceVersion;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SourceVersion}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link SourceVersion} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see SourceVersion
 */
public final class WhatIsNewInSourceVersion
{
  /**
   * Example usage of the new field {@link SourceVersion#RELEASE_12}.
   * @since 12
   * @see SourceVersion#RELEASE_12
   */
  public static final SourceVersion RELEASE_12 = SourceVersion.RELEASE_12;

}
