package whatisnewin.java.text.spi;

import java.text.spi.NumberFormatProvider;
import java.text.NumberFormat;
import java.util.Locale;
import java.text.NumberFormat.Style;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link NumberFormatProvider}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link NumberFormatProvider} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see NumberFormatProvider
 */
public final class WhatIsNewInNumberFormatProvider
{
  /**
   * Example call to new method {@link NumberFormatProvider#getCompactNumberInstance(Locale, Style)}.
   * @since 12
   * @see NumberFormatProvider#getCompactNumberInstance(Locale, Style)
   */
  public NumberFormat getCompactNumberInstance(Locale locale, Style formatStyle)
  {
    NumberFormatProvider testee = $$$();

    NumberFormat result = testee.getCompactNumberInstance(locale, formatStyle);
    return result;
  }

  private NumberFormatProvider $$$()
  {
    return null;
  }
}
