package whatisnewin.java.lang.constant;

import java.lang.constant.MethodHandleDesc;
import java.lang.constant.DirectMethodHandleDesc;
import java.lang.constant.DirectMethodHandleDesc.Kind;
import java.lang.constant.ClassDesc;
import java.lang.constant.MethodTypeDesc;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link MethodHandleDesc}
 * that were newly introduced in Java versions 12.<br>
 *
 * {@link MethodHandleDesc} is a completely new class
 * @since 12
 * @see MethodHandleDesc
 */
public final class WhatIsNewInMethodHandleDesc
{
  /**
   * Example call to new method {@link MethodHandleDesc#of}
   * @since 12
   * @see MethodHandleDesc#of
   */
  public static DirectMethodHandleDesc of(Kind kind, ClassDesc owner, String name, String lookupDescriptor)
  {
    DirectMethodHandleDesc result = MethodHandleDesc.of(kind, owner, name, lookupDescriptor);
    return result;
  }

  /**
   * Example call to new method {@link MethodHandleDesc#ofConstructor}
   * @since 12
   * @see MethodHandleDesc#ofConstructor
   */
  public static DirectMethodHandleDesc ofConstructor(ClassDesc owner, ClassDesc[] paramTypes)
  {
    DirectMethodHandleDesc result = MethodHandleDesc.ofConstructor(owner, paramTypes);
    return result;
  }

  /**
   * Example call to new method {@link MethodHandleDesc#ofField}
   * @since 12
   * @see MethodHandleDesc#ofField
   */
  public static DirectMethodHandleDesc ofField(Kind kind, ClassDesc owner, String fieldName, ClassDesc fieldType)
  {
    DirectMethodHandleDesc result = MethodHandleDesc.ofField(kind, owner, fieldName, fieldType);
    return result;
  }

  /**
   * Example call to new method {@link MethodHandleDesc#asType}
   * @since 12
   * @see MethodHandleDesc#asType
   */
  public MethodHandleDesc asType(MethodTypeDesc type)
  {
    MethodHandleDesc testee = $$$();

    MethodHandleDesc result = testee.asType(type);
    return result;
  }

  /**
   * Example call to new method {@link MethodHandleDesc#invocationType}
   * @since 12
   * @see MethodHandleDesc#invocationType
   */
  public MethodTypeDesc invocationType()
  {
    MethodHandleDesc testee = $$$();

    MethodTypeDesc result = testee.invocationType();
    return result;
  }

  /**
   * Example call to new method {@link MethodHandleDesc#ofMethod}
   * @since 12
   * @see MethodHandleDesc#ofMethod
   */
  public static DirectMethodHandleDesc ofMethod(Kind kind, ClassDesc owner, String name, MethodTypeDesc lookupMethodType)
  {
    DirectMethodHandleDesc result = MethodHandleDesc.ofMethod(kind, owner, name, lookupMethodType);
    return result;
  }

  private MethodHandleDesc $$$()
  {
    return null;
  }
}
