package whatisnewin.java.lang.constant;

import java.lang.constant.ConstantDescs;
import java.lang.constant.DirectMethodHandleDesc;
import java.lang.constant.ClassDesc;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ConstantDescs}
 * that were newly introduced in Java versions 12.<br>
 *
 * {@link ConstantDescs} is a completely new class
 * @since 12
 * @see ConstantDescs
 */
public final class WhatIsNewInConstantDescs
{
  /**
   * Example usage of the new field {@link ConstantDescs#DEFAULT_NAME}
   * @since 12
   * @see ConstantDescs#DEFAULT_NAME
   */
  public static  final String DEFAULT_NAME = ConstantDescs.DEFAULT_NAME;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Object}
   * @since 12
   * @see ConstantDescs#CD_Object
   */
  public static  final ClassDesc CD_Object = ConstantDescs.CD_Object;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_String}
   * @since 12
   * @see ConstantDescs#CD_String
   */
  public static  final ClassDesc CD_String = ConstantDescs.CD_String;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Class}
   * @since 12
   * @see ConstantDescs#CD_Class
   */
  public static  final ClassDesc CD_Class = ConstantDescs.CD_Class;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Number}
   * @since 12
   * @see ConstantDescs#CD_Number
   */
  public static  final ClassDesc CD_Number = ConstantDescs.CD_Number;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Integer}
   * @since 12
   * @see ConstantDescs#CD_Integer
   */
  public static  final ClassDesc CD_Integer = ConstantDescs.CD_Integer;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Long}
   * @since 12
   * @see ConstantDescs#CD_Long
   */
  public static  final ClassDesc CD_Long = ConstantDescs.CD_Long;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Float}
   * @since 12
   * @see ConstantDescs#CD_Float
   */
  public static  final ClassDesc CD_Float = ConstantDescs.CD_Float;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Double}
   * @since 12
   * @see ConstantDescs#CD_Double
   */
  public static  final ClassDesc CD_Double = ConstantDescs.CD_Double;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Short}
   * @since 12
   * @see ConstantDescs#CD_Short
   */
  public static  final ClassDesc CD_Short = ConstantDescs.CD_Short;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Byte}
   * @since 12
   * @see ConstantDescs#CD_Byte
   */
  public static  final ClassDesc CD_Byte = ConstantDescs.CD_Byte;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Character}
   * @since 12
   * @see ConstantDescs#CD_Character
   */
  public static  final ClassDesc CD_Character = ConstantDescs.CD_Character;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Boolean}
   * @since 12
   * @see ConstantDescs#CD_Boolean
   */
  public static  final ClassDesc CD_Boolean = ConstantDescs.CD_Boolean;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Void}
   * @since 12
   * @see ConstantDescs#CD_Void
   */
  public static  final ClassDesc CD_Void = ConstantDescs.CD_Void;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Throwable}
   * @since 12
   * @see ConstantDescs#CD_Throwable
   */
  public static  final ClassDesc CD_Throwable = ConstantDescs.CD_Throwable;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Exception}
   * @since 12
   * @see ConstantDescs#CD_Exception
   */
  public static  final ClassDesc CD_Exception = ConstantDescs.CD_Exception;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Enum}
   * @since 12
   * @see ConstantDescs#CD_Enum
   */
  public static  final ClassDesc CD_Enum = ConstantDescs.CD_Enum;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_VarHandle}
   * @since 12
   * @see ConstantDescs#CD_VarHandle
   */
  public static  final ClassDesc CD_VarHandle = ConstantDescs.CD_VarHandle;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_MethodHandles}
   * @since 12
   * @see ConstantDescs#CD_MethodHandles
   */
  public static  final ClassDesc CD_MethodHandles = ConstantDescs.CD_MethodHandles;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_MethodHandles_Lookup}
   * @since 12
   * @see ConstantDescs#CD_MethodHandles_Lookup
   */
  public static  final ClassDesc CD_MethodHandles_Lookup = ConstantDescs.CD_MethodHandles_Lookup;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_MethodHandle}
   * @since 12
   * @see ConstantDescs#CD_MethodHandle
   */
  public static  final ClassDesc CD_MethodHandle = ConstantDescs.CD_MethodHandle;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_MethodType}
   * @since 12
   * @see ConstantDescs#CD_MethodType
   */
  public static  final ClassDesc CD_MethodType = ConstantDescs.CD_MethodType;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_CallSite}
   * @since 12
   * @see ConstantDescs#CD_CallSite
   */
  public static  final ClassDesc CD_CallSite = ConstantDescs.CD_CallSite;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Collection}
   * @since 12
   * @see ConstantDescs#CD_Collection
   */
  public static  final ClassDesc CD_Collection = ConstantDescs.CD_Collection;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_List}
   * @since 12
   * @see ConstantDescs#CD_List
   */
  public static  final ClassDesc CD_List = ConstantDescs.CD_List;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Set}
   * @since 12
   * @see ConstantDescs#CD_Set
   */
  public static  final ClassDesc CD_Set = ConstantDescs.CD_Set;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_Map}
   * @since 12
   * @see ConstantDescs#CD_Map
   */
  public static  final ClassDesc CD_Map = ConstantDescs.CD_Map;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_ConstantDesc}
   * @since 12
   * @see ConstantDescs#CD_ConstantDesc
   */
  public static  final ClassDesc CD_ConstantDesc = ConstantDescs.CD_ConstantDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_ClassDesc}
   * @since 12
   * @see ConstantDescs#CD_ClassDesc
   */
  public static  final ClassDesc CD_ClassDesc = ConstantDescs.CD_ClassDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_EnumDesc}
   * @since 12
   * @see ConstantDescs#CD_EnumDesc
   */
  public static  final ClassDesc CD_EnumDesc = ConstantDescs.CD_EnumDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_MethodTypeDesc}
   * @since 12
   * @see ConstantDescs#CD_MethodTypeDesc
   */
  public static  final ClassDesc CD_MethodTypeDesc = ConstantDescs.CD_MethodTypeDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_MethodHandleDesc}
   * @since 12
   * @see ConstantDescs#CD_MethodHandleDesc
   */
  public static  final ClassDesc CD_MethodHandleDesc = ConstantDescs.CD_MethodHandleDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_DirectMethodHandleDesc}
   * @since 12
   * @see ConstantDescs#CD_DirectMethodHandleDesc
   */
  public static  final ClassDesc CD_DirectMethodHandleDesc = ConstantDescs.CD_DirectMethodHandleDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_VarHandleDesc}
   * @since 12
   * @see ConstantDescs#CD_VarHandleDesc
   */
  public static  final ClassDesc CD_VarHandleDesc = ConstantDescs.CD_VarHandleDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_MethodHandleDesc_Kind}
   * @since 12
   * @see ConstantDescs#CD_MethodHandleDesc_Kind
   */
  public static  final ClassDesc CD_MethodHandleDesc_Kind = ConstantDescs.CD_MethodHandleDesc_Kind;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_DynamicConstantDesc}
   * @since 12
   * @see ConstantDescs#CD_DynamicConstantDesc
   */
  public static  final ClassDesc CD_DynamicConstantDesc = ConstantDescs.CD_DynamicConstantDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_DynamicCallSiteDesc}
   * @since 12
   * @see ConstantDescs#CD_DynamicCallSiteDesc
   */
  public static  final ClassDesc CD_DynamicCallSiteDesc = ConstantDescs.CD_DynamicCallSiteDesc;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_ConstantBootstraps}
   * @since 12
   * @see ConstantDescs#CD_ConstantBootstraps
   */
  public static  final ClassDesc CD_ConstantBootstraps = ConstantDescs.CD_ConstantBootstraps;

  /**
   * Example usage of the new field {@link ConstantDescs#BSM_PRIMITIVE_CLASS}
   * @since 12
   * @see ConstantDescs#BSM_PRIMITIVE_CLASS
   */
  public static  final DirectMethodHandleDesc BSM_PRIMITIVE_CLASS = ConstantDescs.BSM_PRIMITIVE_CLASS;

  /**
   * Example usage of the new field {@link ConstantDescs#BSM_ENUM_CONSTANT}
   * @since 12
   * @see ConstantDescs#BSM_ENUM_CONSTANT
   */
  public static  final DirectMethodHandleDesc BSM_ENUM_CONSTANT = ConstantDescs.BSM_ENUM_CONSTANT;

  /**
   * Example usage of the new field {@link ConstantDescs#BSM_NULL_CONSTANT}
   * @since 12
   * @see ConstantDescs#BSM_NULL_CONSTANT
   */
  public static  final DirectMethodHandleDesc BSM_NULL_CONSTANT = ConstantDescs.BSM_NULL_CONSTANT;

  /**
   * Example usage of the new field {@link ConstantDescs#BSM_VARHANDLE_FIELD}
   * @since 12
   * @see ConstantDescs#BSM_VARHANDLE_FIELD
   */
  public static  final DirectMethodHandleDesc BSM_VARHANDLE_FIELD = ConstantDescs.BSM_VARHANDLE_FIELD;

  /**
   * Example usage of the new field {@link ConstantDescs#BSM_VARHANDLE_STATIC_FIELD}
   * @since 12
   * @see ConstantDescs#BSM_VARHANDLE_STATIC_FIELD
   */
  public static  final DirectMethodHandleDesc BSM_VARHANDLE_STATIC_FIELD = ConstantDescs.BSM_VARHANDLE_STATIC_FIELD;

  /**
   * Example usage of the new field {@link ConstantDescs#BSM_VARHANDLE_ARRAY}
   * @since 12
   * @see ConstantDescs#BSM_VARHANDLE_ARRAY
   */
  public static  final DirectMethodHandleDesc BSM_VARHANDLE_ARRAY = ConstantDescs.BSM_VARHANDLE_ARRAY;

  /**
   * Example usage of the new field {@link ConstantDescs#BSM_INVOKE}
   * @since 12
   * @see ConstantDescs#BSM_INVOKE
   */
  public static  final DirectMethodHandleDesc BSM_INVOKE = ConstantDescs.BSM_INVOKE;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_int}
   * @since 12
   * @see ConstantDescs#CD_int
   */
  public static  final ClassDesc CD_int = ConstantDescs.CD_int;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_long}
   * @since 12
   * @see ConstantDescs#CD_long
   */
  public static  final ClassDesc CD_long = ConstantDescs.CD_long;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_float}
   * @since 12
   * @see ConstantDescs#CD_float
   */
  public static  final ClassDesc CD_float = ConstantDescs.CD_float;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_double}
   * @since 12
   * @see ConstantDescs#CD_double
   */
  public static  final ClassDesc CD_double = ConstantDescs.CD_double;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_short}
   * @since 12
   * @see ConstantDescs#CD_short
   */
  public static  final ClassDesc CD_short = ConstantDescs.CD_short;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_byte}
   * @since 12
   * @see ConstantDescs#CD_byte
   */
  public static  final ClassDesc CD_byte = ConstantDescs.CD_byte;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_char}
   * @since 12
   * @see ConstantDescs#CD_char
   */
  public static  final ClassDesc CD_char = ConstantDescs.CD_char;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_boolean}
   * @since 12
   * @see ConstantDescs#CD_boolean
   */
  public static  final ClassDesc CD_boolean = ConstantDescs.CD_boolean;

  /**
   * Example usage of the new field {@link ConstantDescs#CD_void}
   * @since 12
   * @see ConstantDescs#CD_void
   */
  public static  final ClassDesc CD_void = ConstantDescs.CD_void;

  /**
   * Example usage of the new field {@link ConstantDescs#NULL}
   * @since 12
   * @see ConstantDescs#NULL
   */
  public static  final java.lang.constant.ConstantDesc NULL = ConstantDescs.NULL;

  /**
   * Example call to new method {@link ConstantDescs#ofConstantBootstrap}
   * @since 12
   * @see ConstantDescs#ofConstantBootstrap
   */
  public static DirectMethodHandleDesc ofConstantBootstrap(ClassDesc owner, String name, ClassDesc returnType, ClassDesc[] paramTypes)
  {
    DirectMethodHandleDesc result = ConstantDescs.ofConstantBootstrap(owner, name, returnType, paramTypes);
    return result;
  }

  /**
   * Example call to new method {@link ConstantDescs#ofCallsiteBootstrap}
   * @since 12
   * @see ConstantDescs#ofCallsiteBootstrap
   */
  public static DirectMethodHandleDesc ofCallsiteBootstrap(ClassDesc owner, String name, ClassDesc returnType, ClassDesc[] paramTypes)
  {
    DirectMethodHandleDesc result = ConstantDescs.ofCallsiteBootstrap(owner, name, returnType, paramTypes);
    return result;
  }

}
