package whatisnewin.java.lang.constant;

import java.lang.constant.DirectMethodHandleDesc;
import java.lang.constant.DirectMethodHandleDesc.Kind;
import java.lang.constant.ClassDesc;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link DirectMethodHandleDesc}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link DirectMethodHandleDesc} is a completely new class.
 * @since 12
 * @see DirectMethodHandleDesc
 */
public final class WhatIsNewInDirectMethodHandleDesc
{
  /**
   * Example call to new method {@link DirectMethodHandleDesc#kind()}.
   * @since 12
   * @see DirectMethodHandleDesc#kind()
   */
  public Kind kind()
  {
    DirectMethodHandleDesc testee = $$$();

    Kind result = testee.kind();
    return result;
  }

  /**
   * Example call to new method {@link DirectMethodHandleDesc#refKind()}.
   * @since 12
   * @see DirectMethodHandleDesc#refKind()
   */
  public int refKind()
  {
    DirectMethodHandleDesc testee = $$$();

    int result = testee.refKind();
    return result;
  }

  /**
   * Example call to new method {@link DirectMethodHandleDesc#owner()}.
   * @since 12
   * @see DirectMethodHandleDesc#owner()
   */
  public ClassDesc owner()
  {
    DirectMethodHandleDesc testee = $$$();

    ClassDesc result = testee.owner();
    return result;
  }

  /**
   * Example call to new method {@link DirectMethodHandleDesc#isOwnerInterface()}.
   * @since 12
   * @see DirectMethodHandleDesc#isOwnerInterface()
   */
  public boolean isOwnerInterface()
  {
    DirectMethodHandleDesc testee = $$$();

    boolean result = testee.isOwnerInterface();
    return result;
  }

  /**
   * Example call to new method {@link DirectMethodHandleDesc#methodName()}.
   * @since 12
   * @see DirectMethodHandleDesc#methodName()
   */
  public String methodName()
  {
    DirectMethodHandleDesc testee = $$$();

    String result = testee.methodName();
    return result;
  }

  /**
   * Example call to new method {@link DirectMethodHandleDesc#lookupDescriptor()}.
   * @since 12
   * @see DirectMethodHandleDesc#lookupDescriptor()
   */
  public String lookupDescriptor()
  {
    DirectMethodHandleDesc testee = $$$();

    String result = testee.lookupDescriptor();
    return result;
  }

  private DirectMethodHandleDesc $$$()
  {
    return null;
  }
}
