package whatisnewin.java.lang.constant;

import java.lang.constant.ConstantDesc;
import java.lang.invoke.MethodHandles.Lookup;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ConstantDesc}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link ConstantDesc} is a completely new class.
 * @since 12
 * @see ConstantDesc
 */
public final class WhatIsNewInConstantDesc
{
  /**
   * Example call to new method {@link ConstantDesc#resolveConstantDesc(Lookup)}.
   * @since 12
   * @see ConstantDesc#resolveConstantDesc(Lookup)
   */
  public Object resolveConstantDesc(Lookup lookup) throws ReflectiveOperationException
  {
    ConstantDesc testee = $$$();

    Object result = testee.resolveConstantDesc(lookup);
    return result;
  }

  private ConstantDesc $$$()
  {
    return null;
  }
}
