package whatisnewin.javax.naming.ldap.spi;

import javax.naming.ldap.spi.LdapDnsProviderResult;
import java.util.List;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link LdapDnsProviderResult}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link LdapDnsProviderResult} is a completely new class.
 * @since 12
 * @see LdapDnsProviderResult
 */
public final class WhatIsNewInLdapDnsProviderResult
{
  /**
   * Example call to new constructor {@link LdapDnsProviderResult#LdapDnsProviderResult(String, List)}.
   * @since 12
   * @see LdapDnsProviderResult#LdapDnsProviderResult(String, List)
   */
  public WhatIsNewInLdapDnsProviderResult(String domainName, List<String> endpoints)
  {
    LdapDnsProviderResult testee = new LdapDnsProviderResult(domainName, endpoints);
  }

  /**
   * Example call to new method {@link LdapDnsProviderResult#getDomainName()}.
   * @since 12
   * @see LdapDnsProviderResult#getDomainName()
   */
  public String getDomainName()
  {
    LdapDnsProviderResult testee = $$$();

    String result = testee.getDomainName();
    return result;
  }

  /**
   * Example call to new method {@link LdapDnsProviderResult#getEndpoints()}.
   * @since 12
   * @see LdapDnsProviderResult#getEndpoints()
   */
  public List<String> getEndpoints()
  {
    LdapDnsProviderResult testee = $$$();

    List<String> result = testee.getEndpoints();
    return result;
  }

  private LdapDnsProviderResult $$$()
  {
    return null;
  }
}
