package whatisnewin.com.sun.source.util;

import com.sun.source.util.SimpleDocTreeVisitor;
import com.sun.source.doctree.SystemPropertyTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SimpleDocTreeVisitor}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link SimpleDocTreeVisitor} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see SimpleDocTreeVisitor
 */
public final class WhatIsNewInSimpleDocTreeVisitor<R, P>
{
  /**
   * Example call to new method {@link SimpleDocTreeVisitor#visitSystemProperty(SystemPropertyTree, Object)}.
   * @since 12
   * @see SimpleDocTreeVisitor#visitSystemProperty(SystemPropertyTree, Object)
   */
  public R visitSystemProperty(SystemPropertyTree node, P p)
  {
    SimpleDocTreeVisitor<R, P> testee = $$$();

    R result = testee.visitSystemProperty(node, p);
    return result;
  }

  private SimpleDocTreeVisitor $$$()
  {
    return null;
  }
}
