package whatisnewin.com.sun.source.util;

import com.sun.source.util.DocTreeFactory;
import com.sun.source.doctree.SystemPropertyTree;
import javax.lang.model.element.Name;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link DocTreeFactory}
 * that were newly introduced in Java versions 12.<br>
 *
 * {@link DocTreeFactory} is an old class but has new fields, constructors or methods
 * @since 9
 * @see DocTreeFactory
 */
public final class WhatIsNewInDocTreeFactory
{
  /**
   * Example call to new method {@link DocTreeFactory#newSystemPropertyTree}
   * @since 12
   * @see DocTreeFactory#newSystemPropertyTree
   */
  public SystemPropertyTree newSystemPropertyTree(Name propertyName)
  {
    DocTreeFactory testee = $$$();

    SystemPropertyTree result = testee.newSystemPropertyTree(propertyName);
    return result;
  }

  private DocTreeFactory $$$()
  {
    return null;
  }
}
