package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.Tree.Kind;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Kind}
 * that were newly introduced in Java version 12.<br>
 *
 * {@link Kind} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see Kind
 */
public final class WhatIsNewInTree$Kind
{
  /**
   * Example usage of the new field {@link Kind#SWITCH_EXPRESSION}.
   * @since 12
   * @see Kind#SWITCH_EXPRESSION
   */
  public static final Kind SWITCH_EXPRESSION = Kind.SWITCH_EXPRESSION;

}
