package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.CaseTree.CaseKind;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link CaseKind}
 * that were newly introduced in Java versions 12.<br>
 *
 * {@link CaseKind} is a completely new class
 * @since 12
 * @see CaseKind
 */
public final class WhatIsNewInCaseTree$CaseKind
{
  /**
   * Example usage of the new field {@link CaseKind#STATEMENT}
   * @since 12
   * @see CaseKind#STATEMENT
   */
  public static  final CaseKind STATEMENT = CaseKind.STATEMENT;

  /**
   * Example usage of the new field {@link CaseKind#RULE}
   * @since 12
   * @see CaseKind#RULE
   */
  public static  final CaseKind RULE = CaseKind.RULE;

  /**
   * Example call to new method {@link CaseKind#values}
   * @since 12
   * @see CaseKind#values
   */
  public static CaseKind[] values()
  {
    CaseKind[] result = CaseKind.values();
    return result;
  }

  /**
   * Example call to new method {@link CaseKind#valueOf}
   * @since 12
   * @see CaseKind#valueOf
   */
  public static CaseKind valueOf(String name)
  {
    CaseKind result = CaseKind.valueOf(name);
    return result;
  }

}
